services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  spark:
    build: .
    container_name: spark
    depends_on:
      - minio
    ports:
      - "4040:4040"
    volumes:
      - .:/bees_breweries_ingestion
      - ./data:/data
    working_dir: /bees_breweries_ingestion
    command: [ "tail", "-f", "/dev/null" ]

volumes:
  minio-data: